// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ualebznoscdhhhysxjix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhbGViem5vc2NkaGhoeXN4aml4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMzIyMjksImV4cCI6MjA3NDYwODIyOX0.ZihjR3LdlVVriiI9JIxdGwXEBmwrvFKB869MnQt-qEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});